import Link from "next/link";
import {
  Building2,
  HeartPulse,
  AlertTriangle,
  ShieldAlert,
  Clock,
  HardHat,
  ArrowRight,
  BellRing,
  CheckCircle2,
} from "lucide-react";
import {
  schools,
  alerts,
  contractorVisits,
  tickets,
  portfolioStats,
  schoolName,
} from "@/lib/data";
import {
  Card,
  StatCard,
  StatusDot,
  HealthBar,
  Badge,
  PageHeader,
} from "@/components/ui";

const severityRing: Record<string, string> = {
  critical: "border-l-red-500 bg-red-50/40",
  warning: "border-l-amber-500 bg-amber-50/40",
  info: "border-l-blue-500 bg-blue-50/40",
};

const alertIcon: Record<string, React.ReactNode> = {
  contractor: <HardHat size={16} />,
  compliance: <ShieldAlert size={16} />,
  sla: <Clock size={16} />,
  incident: <BellRing size={16} />,
  escalation: <AlertTriangle size={16} />,
};

export default function Dashboard() {
  const stats = portfolioStats();
  const sortedTickets = [...tickets].sort(
    (a, b) => a.slaHoursLeft - b.slaHoursLeft
  );

  return (
    <div className="mx-auto max-w-7xl">
      <PageHeader
        title="Operations Overview"
        subtitle="Real-time visibility across your estate — North & South clusters"
        action={
          <Link
            href="/assistant"
            className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-indigo-700"
          >
            Ask Caretaker AI
          </Link>
        }
      />

      {/* Stat row */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">
        <StatCard
          label="Schools"
          value={stats.totalSchools}
          sub={`${stats.totalPupils.toLocaleString()} pupils`}
          icon={<Building2 size={20} />}
        />
        <StatCard
          label="Avg. Health"
          value={`${stats.avgHealth}%`}
          sub="compliance score"
          tone={stats.avgHealth >= 75 ? "success" : "warning"}
          icon={<HeartPulse size={20} />}
        />
        <StatCard
          label="Open Incidents"
          value={stats.openIncidents}
          sub="across all sites"
          tone="warning"
          icon={<AlertTriangle size={20} />}
        />
        <StatCard
          label="Overdue Compliance"
          value={stats.overdueCompliance}
          sub="legal risk"
          tone="danger"
          icon={<ShieldAlert size={20} />}
        />
        <StatCard
          label="SLA at Risk"
          value={stats.slaAtRisk}
          sub="breaching < 12h"
          tone="danger"
          icon={<Clock size={20} />}
        />
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* Live alerts */}
        <Card className="lg:col-span-2">
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
            <div className="flex items-center gap-2">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-red-50 text-red-600">
                <BellRing size={15} />
              </span>
              <h2 className="font-semibold text-slate-900">Live Alerts</h2>
              <span className="rounded-full bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-700">
                {alerts.length}
              </span>
            </div>
            <span className="text-xs text-slate-400">Auto-generated by AI</span>
          </div>
          <div className="divide-y divide-slate-100">
            {alerts.map((a) => (
              <div
                key={a.id}
                className={`flex gap-3 border-l-4 px-5 py-3.5 ${severityRing[a.severity]}`}
              >
                <span
                  className={`mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg ${
                    a.severity === "critical"
                      ? "bg-red-100 text-red-600"
                      : a.severity === "warning"
                        ? "bg-amber-100 text-amber-600"
                        : "bg-blue-100 text-blue-600"
                  }`}
                >
                  {alertIcon[a.type]}
                </span>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-sm font-semibold text-slate-900">
                      {a.title}
                    </p>
                    <span className="shrink-0 text-xs text-slate-400">
                      {a.timeLabel}
                    </span>
                  </div>
                  <p className="mt-0.5 text-sm text-slate-600">{a.detail}</p>
                  <p className="mt-1 text-xs font-medium text-slate-400">
                    {schoolName(a.schoolId)}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Upcoming visits */}
        <Card>
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
            <div className="flex items-center gap-2">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600">
                <HardHat size={15} />
              </span>
              <h2 className="font-semibold text-slate-900">Upcoming Visits</h2>
            </div>
            <Link
              href="/contractors"
              className="text-xs font-medium text-indigo-600 hover:underline"
            >
              View all
            </Link>
          </div>
          <div className="divide-y divide-slate-100">
            {contractorVisits.slice(0, 5).map((v) => (
              <div key={v.id} className="px-5 py-3.5">
                <div className="flex items-center justify-between gap-2">
                  <p className="text-sm font-semibold text-slate-900">
                    {v.contractor}
                  </p>
                  {v.notified ? (
                    <Badge tone="green">Notified</Badge>
                  ) : (
                    <Badge tone="red">Not notified</Badge>
                  )}
                </div>
                <p className="mt-0.5 text-sm text-slate-600">{v.purpose}</p>
                <div className="mt-1 flex items-center justify-between text-xs text-slate-400">
                  <span>{schoolName(v.schoolId)}</span>
                  <span className="font-medium text-slate-500">
                    {v.whenLabel}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* School status */}
        <Card className="lg:col-span-2">
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
            <h2 className="font-semibold text-slate-900">Site Health</h2>
            <Link
              href="/schools"
              className="flex items-center gap-1 text-xs font-medium text-indigo-600 hover:underline"
            >
              All schools <ArrowRight size={13} />
            </Link>
          </div>
          <div className="divide-y divide-slate-100">
            {schools.map((s) => (
              <Link
                key={s.id}
                href="/schools"
                className="flex items-center gap-4 px-5 py-4 transition hover:bg-slate-50"
              >
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <p className="truncate font-medium text-slate-900">
                      {s.name}
                    </p>
                    <StatusDot status={s.status} />
                  </div>
                  <p className="text-xs text-slate-400">
                    {s.region} · {s.buildings} buildings · {s.pupils} pupils
                  </p>
                </div>
                <div className="hidden w-40 sm:block">
                  <div className="mb-1 flex justify-between text-xs">
                    <span className="text-slate-400">Health</span>
                    <span className="font-semibold text-slate-700">
                      {s.healthScore}%
                    </span>
                  </div>
                  <HealthBar score={s.healthScore} />
                </div>
                <div className="hidden text-right md:block">
                  <p className="text-xs text-slate-400">Issues</p>
                  <p className="text-sm font-semibold text-slate-700">
                    {s.openIncidents + s.overdueTasks}
                  </p>
                </div>
              </Link>
            ))}
          </div>
        </Card>

        {/* SLA watch */}
        <Card>
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
            <h2 className="font-semibold text-slate-900">SLA Watch</h2>
            <Link
              href="/helpdesk"
              className="text-xs font-medium text-indigo-600 hover:underline"
            >
              Help desk
            </Link>
          </div>
          <div className="divide-y divide-slate-100">
            {sortedTickets.slice(0, 5).map((t) => {
              const breached = t.slaHoursLeft < 0;
              const risk = t.slaHoursLeft <= 12;
              return (
                <div key={t.id} className="px-5 py-3.5">
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-mono text-xs text-slate-400">
                      {t.id}
                    </span>
                    <span
                      className={`flex items-center gap-1 text-xs font-semibold ${
                        breached
                          ? "text-red-600"
                          : risk
                            ? "text-amber-600"
                            : "text-emerald-600"
                      }`}
                    >
                      {breached ? (
                        <AlertTriangle size={12} />
                      ) : risk ? (
                        <Clock size={12} />
                      ) : (
                        <CheckCircle2 size={12} />
                      )}
                      {t.slaLabel}
                    </span>
                  </div>
                  <p className="mt-1 truncate text-sm font-medium text-slate-800">
                    {t.title}
                  </p>
                  <p className="text-xs text-slate-400">
                    {schoolName(t.schoolId)} · {t.priority}
                  </p>
                </div>
              );
            })}
          </div>
        </Card>
      </div>
    </div>
  );
}
